name: orpheus_dart
description: A server app using the shelf package and Docker.
version: 3.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2
  shelf_gzip: ^4.1.0
  shelf_swagger_ui: ^1.0.0+2
  http: ^1.2.2
  youtube_explode_dart: ^2.5.2
  mongo_dart: ^0.10.2
  dotenv: ^4.2.0
  html: ^0.15.4
  uuid: ^4.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
